variable "common_tags" {}
variable "resource_prefix" {}
variable "aws_region" {}
variable "container_name" {}
variable "public_subnet_ids" {}
variable "sg_ecs_service_id" {}
variable "ecs_task_execution_role_arn" {}
variable "aws_ecr_repository_url" {}
variable "alb_target_group_arn" {}
